---
name: DBIx-RetryOverDisconnects
version: 0.01
author:
  - 'Pronin Oleg <syber@cpan.org>'
abstract: DBI wrapper that helps to deal with databases connection problems
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 1.44
  Exception::Class: 1.23
provides:
  DBIx::RetryOverDisconnects:
    file: lib/DBIx/RetryOverDisconnects.pm
    version: 0.01
  DBIx::RetryOverDisconnects::db:
    file: lib/DBIx/RetryOverDisconnects.pm
  DBIx::RetryOverDisconnects::st:
    file: lib/DBIx/RetryOverDisconnects.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
